package vezh_bank.persistence.providers.card;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;
import vezh_bank.enums.CardStatus;

import java.util.stream.Stream;

public class SelectCardWithPageArgumentsProvider implements ArgumentsProvider {
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) throws Exception {
        return Stream.of(
                Arguments.of(1, 4, "", "", "", "", "", "", 4),
                Arguments.of(2, 4, "", "", "", "", "", "", 4),
                Arguments.of(1, 4, "54", "", "", "", "", "", 1),
                Arguments.of(1, 4, "666", "", "", "", "", "", 1),
                Arguments.of(1, 4, "", "User", "", "", "", "", 4),
                Arguments.of(2, 4, "", "User", "", "", "", "", 4),
                Arguments.of(1, 4, "", "User data", "", "", "", "", 4),
                Arguments.of(2, 4, "", "User data", "", "", "", "", 4),
                Arguments.of(1, 4, "", "User data 1", "", "", "", "", 3),
                Arguments.of(1, 4, "", "", "", "10", "", "", 2),
                Arguments.of(1, 4, "", "", "", "102", "", "", 2),
                Arguments.of(1, 4, "", "", "", "1020", "", "", 1),
                Arguments.of(1, 4, "", "", "", "", "643", "", 3),
                Arguments.of(1, 4, "", "", "", "", "RUB", "", 3),
                Arguments.of(1, 4, "", "", "", "", "", CardStatus.ACTIVE.toString(), 4),
                Arguments.of(2, 4, "", "", "", "", "", CardStatus.ACTIVE.toString(), 1),
                Arguments.of(1, 4, "", "", "", "", "", CardStatus.BLOCKED.toString(), 2),
                Arguments.of(1, 4, "", "", "", "", "", CardStatus.EXPIRED.toString(), 1),
                Arguments.of(1, 4, "54", "User", "", "", "", "", 1),
                Arguments.of(1, 4, "666", "User", "", "", "", "", 1),
                Arguments.of(1, 4, "54", "User data", "", "", "", "", 1),
                Arguments.of(1, 4, "666", "User data", "", "", "", "", 1),
                Arguments.of(1, 4, "54", "User data 1", "", "", "", "", 1),
                Arguments.of(1, 4, "666", "User data 1", "", "", "", "", 1),
                Arguments.of(1, 4, "54", "", "", "10", "", "", 1),
                Arguments.of(1, 4, "666", "", "", "10", "", "", 1),
                Arguments.of(1, 4, "54", "", "", "102", "", "", 1),
                Arguments.of(1, 4, "666", "", "", "102", "", "", 1),
                Arguments.of(1, 4, "54", "", "", "1020", "", "", 1),
                Arguments.of(1, 4, "666", "", "", "1020", "", "", 0),
                Arguments.of(1, 4, "54", "", "", "", "643", "", 1),
                Arguments.of(1, 4, "666", "", "", "", "643", "", 0),
                Arguments.of(1, 4, "54", "", "", "", "RUB", "", 1),
                Arguments.of(1, 4, "666", "", "", "", "RUB", "", 0),
                Arguments.of(1, 4, "54", "", "", "", "", CardStatus.ACTIVE.toString(), 1),
                Arguments.of(1, 4, "666", "", "", "", "", CardStatus.ACTIVE.toString(), 1),
                Arguments.of(1, 4, "54", "", "", "", "", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "666", "", "", "", "", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "54", "", "", "", "", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "666", "", "", "", "", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "", "User", "", "10", "", "", 2),
                Arguments.of(1, 4, "", "User", "", "102", "", "", 2),
                Arguments.of(1, 4, "", "User", "", "1020", "", "", 1),
                Arguments.of(1, 4, "", "User", "", "", "643", "", 3),
                Arguments.of(1, 4, "", "User", "", "", "RUB", "", 3),
                Arguments.of(1, 4, "", "User", "", "", "", CardStatus.ACTIVE.toString(), 4),
                Arguments.of(2, 4, "", "User", "", "", "", CardStatus.ACTIVE.toString(), 1),
                Arguments.of(1, 4, "", "User", "", "", "", CardStatus.BLOCKED.toString(), 2),
                Arguments.of(1, 4, "", "User", "", "", "", CardStatus.EXPIRED.toString(), 1),
                Arguments.of(1, 4, "", "User data", "", "10", "", "", 2),
                Arguments.of(1, 4, "", "User data", "", "102", "", "", 2),
                Arguments.of(1, 4, "", "User data", "", "1020", "", "", 1),
                Arguments.of(1, 4, "", "User data", "", "", "643", "", 3),
                Arguments.of(1, 4, "", "User data", "", "", "RUB", "", 3),
                Arguments.of(1, 4, "", "User data", "", "", "", CardStatus.ACTIVE.toString(), 4),
                Arguments.of(2, 4, "", "User data", "", "", "", CardStatus.ACTIVE.toString(), 1),
                Arguments.of(1, 4, "", "User data", "", "", "", CardStatus.BLOCKED.toString(), 2),
                Arguments.of(1, 4, "", "User data", "", "", "", CardStatus.EXPIRED.toString(), 1),
                Arguments.of(1, 4, "", "User data 1", "", "10", "", "", 2),
                Arguments.of(1, 4, "", "User data 1", "", "102", "", "", 2),
                Arguments.of(1, 4, "", "User data 1", "", "1020", "", "", 1),
                Arguments.of(1, 4, "", "User data 1", "", "", "643", "", 1),
                Arguments.of(1, 4, "", "User data 1", "", "", "RUB", "", 1),
                Arguments.of(1, 4, "", "User data 1", "", "", "", CardStatus.ACTIVE.toString(), 3),
                Arguments.of(1, 4, "", "User data 1", "", "", "", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "", "User data 1", "", "", "", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "10", "643", "", 1),
                Arguments.of(1, 4, "", "", "", "102", "643", "", 1),
                Arguments.of(1, 4, "", "", "", "1020", "643", "", 1),
                Arguments.of(1, 4, "", "", "", "10", "RUB", "", 1),
                Arguments.of(1, 4, "", "", "", "102", "RUB", "", 1),
                Arguments.of(1, 4, "", "", "", "1020", "RUB", "", 1),
                Arguments.of(1, 4, "", "", "", "10", "", CardStatus.ACTIVE.toString(), 2),
                Arguments.of(1, 4, "", "", "", "10", "", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "10", "", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "102", "", CardStatus.ACTIVE.toString(), 2),
                Arguments.of(1, 4, "", "", "", "102", "", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "102", "", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "1020", "", CardStatus.ACTIVE.toString(), 1),
                Arguments.of(1, 4, "", "", "", "1020", "", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "1020", "", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "", "643", CardStatus.ACTIVE.toString(), 3),
                Arguments.of(1, 4, "", "", "", "", "643", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "", "643", CardStatus.EXPIRED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "", "RUB", CardStatus.ACTIVE.toString(), 3),
                Arguments.of(1, 4, "", "", "", "", "RUB", CardStatus.BLOCKED.toString(), 0),
                Arguments.of(1, 4, "", "", "", "", "RUB", CardStatus.EXPIRED.toString(), 0)
        );
    }
}
