package vezh_bank.controller.user.providers.update;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;
import vezh_bank.constants.ExceptionMessages;
import vezh_bank.constants.RequestParams;

import java.util.stream.Stream;

public class RequestParamsArgumentsProvider implements ArgumentsProvider {

    /**
     * String description, String password, String country, String region, String city,
     *                                   String street, String house, String housePart, String room, String firstName,
     *                                   String middleName, String patronymic, String contactNumber, String email,
     *                                   String cardsOnPage, String currenciesOnPage, String eventsOnPage,
     *                                   String paymentsOnPage, String transactionsOnPage, String usersOnPage,
     *                                   String userRequestsOnPage, String expectedErrorMessage
     * @param extensionContext
     * @return
     * @throws Exception
     */
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) throws Exception {
        return Stream.of(
                Arguments.of("Password is NULL", null, "Temeria", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.PASSWORD)),
                Arguments.of("Password is too short", "1", "Temeria", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PASSWORD)),
                Arguments.of("Password is too long", "11111 11111 11111 11111", "Temeria", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PASSWORD)),

                Arguments.of("Country is NULL", "password", null, "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.COUNTRY)),
                Arguments.of("Country is too short", "password", "1", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.COUNTRY)),
                Arguments.of("Country is too long", "password", "MyCountryMyCountryMyCountryMyCountryMyCountryMyCountry",
                        "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.COUNTRY)),
                Arguments.of("Country has wrong chars", "password", "Temer!ya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.COUNTRY)),
                Arguments.of("Country has number", "password", "Temer1ya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.COUNTRY)),

                Arguments.of("Region is NULL", "password", "Temerya", null, "Vizima",  "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.REGION)),
                Arguments.of("Region is too short", "password", "Temerya", "2", "Vizima",  "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.REGION)),
                Arguments.of("Region is too long", "password", "Temerya",
                        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.REGION)),
                Arguments.of("Region has wrong chars", "password", "Temerya", "Vizim@",  "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.REGION)),

                Arguments.of("City is NULL", "password", "Temerya", "Vizima", null, "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.CITY)),
                Arguments.of("City is too short", "password", "Temerya", "Vizima", "1", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CITY)),
                Arguments.of("City is too long", "password", "Temerya", "Vizima", "NewYorkNewYorkNewYorkNewYorkNewYorkNewYorkNewYorkNewYork",
                        "Dabovskaya", "3", "1", "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CITY)),
                Arguments.of("City has wrong chars", "password", "Temerya", "Vizima", "Vizim@", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CITY)),

                Arguments.of("Street is NULL", "password", "Temerya", "Vizima", "Vizima", null, "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.STREET)),
                Arguments.of("Street is too short", "password", "Temerya", "Vizima", "Vizima", "D", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.STREET)),
                Arguments.of("Street is too long", "password", "Temerya", "Vizima", "Vizima",
                        "DabovskayaDabovskayaDabovskayaDabovskayaDabovskayaDabovskayaDabovskayaDabovskayaDabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.STREET)),

                Arguments.of("House is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", null, "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.HOUSE)),
                Arguments.of("House can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "t", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.HOUSE)),
                Arguments.of("House is 0", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "0", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.HOUSE)),

                Arguments.of("House part can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "y",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.HOUSE_PART)),
                Arguments.of("House part is 0", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "0",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.HOUSE_PART)),

                Arguments.of("Room is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        null, "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.ROOM)),
                Arguments.of("Room can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "rt", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.ROOM)),
                Arguments.of("Room is 0", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "0", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.ROOM)),

                Arguments.of("First name is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", null, "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.FIRST_NAME)),
                Arguments.of("First name is too short", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "G", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.FIRST_NAME)),
                Arguments.of("First name is too long", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "GeraltGeraltGeraltGeraltGeralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.FIRST_NAME)),
                Arguments.of("First name has number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt1", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.FIRST_NAME)),
                Arguments.of("First name has wrong chars", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Ger@lt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.FIRST_NAME)),

                Arguments.of("Middle name is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", null, "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.MIDDLE_NAME)),
                Arguments.of("Middle name is too short", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "f", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.MIDDLE_NAME)),
                Arguments.of("Middle name is too long", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "fromfromfromfromfromfromfromfromfrom", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.MIDDLE_NAME)),
                Arguments.of("Middle name has number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from1", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.MIDDLE_NAME)),
                Arguments.of("Middle name has wrong chars", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "fr@m", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.MIDDLE_NAME)),

                Arguments.of("Patronymic is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", null, "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.PATRONYMIC)),
                Arguments.of("Patronymic is too short", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "R", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PATRONYMIC)),
                Arguments.of("Patronymic is too long", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "RiviaRiviaRiviaRiviaRiviaRiviaRiviaRiviaRivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PATRONYMIC)),
                Arguments.of("Patronymic has number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia1", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PATRONYMIC)),
                Arguments.of("Patronymic has wrong chars", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivi@", "+375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PATRONYMIC)),

                Arguments.of("Contact number is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", null, "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.CONTACT_NUMBER)),
                Arguments.of("Contact number has no +", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CONTACT_NUMBER)),
                Arguments.of("Contact number has letter", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008a63412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CONTACT_NUMBER)),
                Arguments.of("Contact number has wrong char", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008@63412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CONTACT_NUMBER)),
                Arguments.of("Contact number is too short", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CONTACT_NUMBER)),
                Arguments.of("Contact number is too long", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412375008963412", "fuckYennifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CONTACT_NUMBER)),

                Arguments.of("Email is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EMAIL)),
                Arguments.of("Email has point before @", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYe.nnifer@kaermorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EMAIL)),
                Arguments.of("Email has two @", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kae@rmorhan.org", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EMAIL)),
                Arguments.of("Email has two points after @", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.or.g", "20",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EMAIL)),

                Arguments.of("Cards on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", null,
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.CARDS_ON_PAGE)),
                Arguments.of("Cards on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CARDS_ON_PAGE)),
                Arguments.of("Cards on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "f",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CARDS_ON_PAGE)),
                Arguments.of("Cards on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "9",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CARDS_ON_PAGE)),
                Arguments.of("Cards on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "101",
                        "20", "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CARDS_ON_PAGE)),

                Arguments.of("Currencies on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", null,
                        "20", "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.CURRENCIES_ON_PAGE)),
                Arguments.of("Currencies on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "",
                        "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CURRENCIES_ON_PAGE)),
                Arguments.of("Currencies on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "g",
                        "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CURRENCIES_ON_PAGE)),
                Arguments.of("Currencies on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "9",
                        "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CURRENCIES_ON_PAGE)),
                Arguments.of("Currencies on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "101",
                        "20", "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.CURRENCIES_ON_PAGE)),

                Arguments.of("Events on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", null,
                        "20", "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.EVENTS_ON_PAGE)),
                Arguments.of("Events on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "",
                        "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EVENTS_ON_PAGE)),
                Arguments.of("Events on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "g",
                        "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EVENTS_ON_PAGE)),
                Arguments.of("Events on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "9",
                        "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EVENTS_ON_PAGE)),
                Arguments.of("Events on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "101",
                        "20", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.EVENTS_ON_PAGE)),

                Arguments.of("Payments on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        null, "20", "20", "20", ExceptionMessages.missingParameter(RequestParams.PAYMENTS_ON_PAGE)),
                Arguments.of("Payments on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "20",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PAYMENTS_ON_PAGE)),
                Arguments.of("Payments on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "h", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PAYMENTS_ON_PAGE)),
                Arguments.of("Payments on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "9", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PAYMENTS_ON_PAGE)),
                Arguments.of("Payments on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "101", "20", "20", "20", ExceptionMessages.invalidParameter(RequestParams.PAYMENTS_ON_PAGE)),

                Arguments.of("Transactions on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", null, "20", "20", ExceptionMessages.missingParameter(RequestParams.TRANSACTIONS_ON_PAGE)),
                Arguments.of("Transactions on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "20",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "", "20", "20", ExceptionMessages.invalidParameter(RequestParams.TRANSACTIONS_ON_PAGE)),
                Arguments.of("Transactions on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "h", "20", "20", ExceptionMessages.invalidParameter(RequestParams.TRANSACTIONS_ON_PAGE)),
                Arguments.of("Transactions on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "9", "20", "20", ExceptionMessages.invalidParameter(RequestParams.TRANSACTIONS_ON_PAGE)),
                Arguments.of("Transactions on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "101", "20", "20", ExceptionMessages.invalidParameter(RequestParams.TRANSACTIONS_ON_PAGE)),

                Arguments.of("Users on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", null, "20", ExceptionMessages.missingParameter(RequestParams.USERS_ON_PAGE)),
                Arguments.of("Users on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "20",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "", "20", ExceptionMessages.invalidParameter(RequestParams.USERS_ON_PAGE)),
                Arguments.of("Users on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "h", "20", ExceptionMessages.invalidParameter(RequestParams.USERS_ON_PAGE)),
                Arguments.of("Users on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "9", "20", ExceptionMessages.invalidParameter(RequestParams.USERS_ON_PAGE)),
                Arguments.of("Users on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "101", "20", ExceptionMessages.invalidParameter(RequestParams.USERS_ON_PAGE)),

                Arguments.of("User requests on page is NULL", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "20", null, ExceptionMessages.missingParameter(RequestParams.USER_REQUESTS_ON_PAGE)),
                Arguments.of("User requests on page is empty", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "20",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "20", "", ExceptionMessages.invalidParameter(RequestParams.USER_REQUESTS_ON_PAGE)),
                Arguments.of("User requests on page can't be a number", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "20", "h", ExceptionMessages.invalidParameter(RequestParams.USER_REQUESTS_ON_PAGE)),
                Arguments.of("User requests on page less that allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "20", "9", ExceptionMessages.invalidParameter(RequestParams.USER_REQUESTS_ON_PAGE)),
                Arguments.of("User requests on page bigger than allowed", "password", "Temerya", "Vizima", "Vizima", "Dabovskaya", "3", "1",
                        "666", "Geralt", "from", "Rivia", "+375008963412", "fuckYennifer@kaermorhan.org", "20", "20", "20",
                        "20", "20", "20", "101", ExceptionMessages.invalidParameter(RequestParams.USER_REQUESTS_ON_PAGE))
        );
    }
}
