package vezh_bank.controller.providers;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;

import static java.lang.String.format;
import static vezh_bank.constants.ExceptionMessages.INVALID_PARAMETER;
import static vezh_bank.constants.ExceptionMessages.MISSING_PARAMETER;
import static vezh_bank.constants.RequestParams.*;

public class RegisterUserFailArgumentsProvider implements ArgumentsProvider {

    /**
     * Arguments: description, login, password, role, country, region, city, street, house, room, firstName,
     * middleName, patronymic, birthDate, contactNumber, email, expectedErrorMessage
     * @param extensionContext
     * @return
     * @throws Exception
     */
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) throws Exception {
        return Stream.of(
                Arguments.of("Login is NULL", null, "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, LOGIN)),
                Arguments.of("Login is empty", "", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, LOGIN)),
                Arguments.of("Login is shorter than allowed", "tes", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, LOGIN)),
                Arguments.of("Login is longer than allowed", "BenderBenderBenderBen", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, LOGIN)),
                Arguments.of("Login is contains wrong chars", "Vezhny!", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, LOGIN)),
                Arguments.of("Password is NULL", "Vezhny", null, "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, PASSWORD)),
                Arguments.of("Password is empty", "Vezhny", "", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PASSWORD)),
                Arguments.of("Password is shorter than allowed", "Vezhny", "12345", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PASSWORD)),
                Arguments.of("Password is longer than allowed", "Vezhny", "12345678901234567", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PASSWORD)),
                Arguments.of("Role is NULL", "Vezhny", "password", null, "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, ROLE)),
                Arguments.of("Role is empty", "Vezhny", "password", "", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, ROLE)),
                Arguments.of("Role is different", "Vezhny", "password", "CUSTOM", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, ROLE)),
                Arguments.of("First name is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", null, "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, FIRST_NAME)),
                Arguments.of("First name is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, FIRST_NAME)),
                Arguments.of("First name is shorter than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "a", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, FIRST_NAME)),
                Arguments.of("First name is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "ArtsiomArtsiomArtsiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, FIRST_NAME)),
                Arguments.of("First name has wrong chars", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Artsiom3", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, FIRST_NAME)),
                Arguments.of("Middle name is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", null, "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, MIDDLE_NAME)),
                Arguments.of("Middle name is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, MIDDLE_NAME)),
                Arguments.of("Middle name is shorter than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "v", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, MIDDLE_NAME)),
                Arguments.of("Middle name is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "VezhnavetsVezhnavetsV", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, MIDDLE_NAME)),
                Arguments.of("Middle name has wrong chars", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnav2ets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, MIDDLE_NAME)),
                Arguments.of("Patronymic is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", null, "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, PATRONYMIC)),
                Arguments.of("Patronymic is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PATRONYMIC)),
                Arguments.of("Patronymic is shorter than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "V", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PATRONYMIC)),
                Arguments.of("Patronymic is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "VadimovichVadimovichV", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PATRONYMIC)),
                Arguments.of("Patronymic has wrong chars", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovi4", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, PATRONYMIC)),
                Arguments.of("Birth date is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", null,
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, BIRTH_DATE)),
                Arguments.of("Birth date is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, BIRTH_DATE)),
                Arguments.of("Birth date has wrong pattern", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10111992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, BIRTH_DATE)),
                Arguments.of("User is too young", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.2017",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, BIRTH_DATE)),
                Arguments.of("Country is NULL", "Vezhny", "password", "CLIENT", null, "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, COUNTRY)),
                Arguments.of("Country is empty", "Vezhny", "password", "CLIENT", "", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, COUNTRY)),
                Arguments.of("Country is shorter than allowed", "Vezhny", "password", "CLIENT", "BY", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, COUNTRY)),
                Arguments.of("Country is longer than allowed", "Vezhny", "password", "CLIENT", "BelarusBelarusBelarusBelarusBelarusBelarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, COUNTRY)),
                Arguments.of("Country has wrong chars", "Vezhny", "password", "CLIENT", "Belarus1", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, COUNTRY)),
                Arguments.of("Region is NULL", "Vezhny", "password", "CLIENT", "Belarus", null, "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, REGION)),
                Arguments.of("Region is empty", "Vezhny", "password", "CLIENT", "Belarus", "", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, REGION)),
                Arguments.of("Region is shorter than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Hom", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, REGION)),
                Arguments.of("Region is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "HomieHomieHomieHomieHomieHomieHomieHomieHomieHomiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, REGION)),
                Arguments.of("Region has wrong chars", "Vezhny", "password", "CLIENT", "Belarus", "Homiel!", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, REGION)),
                Arguments.of("City is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", null,
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, CITY)),
                Arguments.of("City is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, CITY)),
                Arguments.of("City is shorter than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "jams",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, CITY)),
                Arguments.of("City is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "SvetlogorskSvetlogorskSvetlogorskSvetlogorskSve",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, CITY)),
                Arguments.of("City has wrong chars", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk!",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, CITY)),
                Arguments.of("Street is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        null, "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, STREET)),
                Arguments.of("Street is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, STREET)),
                Arguments.of("Street is shorted than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lu", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, STREET)),
                Arguments.of("Street is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "LunacharskogoLunacharskogoLunacharskogoLunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, STREET)),
                Arguments.of("House is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", null, "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, HOUSE)),
                Arguments.of("House is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, HOUSE)),
                Arguments.of("House can't be a number", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "a", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, HOUSE)),
                Arguments.of("House has invalid value", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "-2", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, HOUSE)),
                Arguments.of("Room is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", null, "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(MISSING_PARAMETER, ROOM)),
                Arguments.of("Room is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, ROOM)),
                Arguments.of("Room can't be a number", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "j", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, ROOM)),
                Arguments.of("Room has invalid value", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "-2", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhny@gmail.com", format(INVALID_PARAMETER, ROOM)),
                Arguments.of("Contact number is NULL", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        null, "vezhny@gmail.com", format(MISSING_PARAMETER, CONTACT_NUMBER)),
                Arguments.of("Contact number is empty", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "", "vezhny@gmail.com", format(INVALID_PARAMETER, CONTACT_NUMBER)),
                Arguments.of("Contact number can't be a number", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375r", "vezhny@gmail.com", format(INVALID_PARAMETER, CONTACT_NUMBER)),
                Arguments.of("Contact number is shorter than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293", "vezhny@gmail.com", format(INVALID_PARAMETER, CONTACT_NUMBER)),
                Arguments.of("Contact number is longer than allowed", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+3752939562233333", "vezhny@gmail.com", format(INVALID_PARAMETER, CONTACT_NUMBER)),
                Arguments.of("Email has wrong format", "Vezhny", "password", "CLIENT", "Belarus", "Homiel", "Svetlogorsk",
                        "Lunacharskogo", "30", "213", "Arstiom", "Vezhnavets", "Vadimovich", "10.11.1992",
                        "+375293956223", "vezhnygmail.com", format(INVALID_PARAMETER, EMAIL))
        );
    }
}
